apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTVRBdwpNRFE0TkRKYUZ3MDBNakEyTVRBd01EUTROREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdTlmMFlPZWllRlZBLzJDUkFiM1RXT3loUHZyUDlpaGxVMURISW9ndEduSkcyNGRWSAoxUlZ2Rm16SElSL0xGWjRRZ0d6eFFnRTVYaGVCNDJxKzg3U0ZoclpOQnYvK090L2FaVEVzTGJtK2RkYTI1eWNOClR6VG9KQi9kOTBzdkxVdll2TVFVcUNZbk82OTU1N2Y5MXppalFkb2JJUGIvRjRLSDRnVHIwUlFjWmFMMVFUWDcKeGxRTVBydWU1YlRmYTBGMWNzcTllQ1JQMU9oMVRHLzJYbEluZXpOczc5RTZMcHc3a2JGdVJWT3kvWDR4YmVYWAp4V3BQV2RTTVBoZFFSQzRoMEVXOUlJanl3MTZiUldwSDN2Q0E4VExuY2xnb3YxNTBPbmVHQnErdnRWYmRvMFBQCm1YUEU0cGRLVUNVRmw2bDcrZCtnV21YZlFTejJWTEdmVnNMZkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFFdE0vOFJ6N0VOYXhNT3YvYwozNXJuNFpZTUNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFBQXoxUEFydENXOHU5ckJNbmV3SGU0UnI4ZTdLClo3eXF3N205YkMrQ1R3VjRpNkJ5MDNJdU5ZZDdLUU9EcTJuOHFINTBHU2ZuczlRQU9JV1lFSCt6UkkyRlR2aVoKRnY5dzNZSEpvbTUrdzkxWVo3UmxyY1RhZXJ4VlhBeTFzSkNBa0ZpeG1JNzBWTjBuS3dFTmhMVG9LcXYwUGlYSwo3UG5ZVFJuZzJjMG5TRUt1TExSSUszR0tEU20yaXM1Tk0xYjFhNVNGLzFBbURsK3RWcHpTK3pRMEtBUjdUbWNpCnlJd2p6NTF3ZGFlVmpMVHNwdC9JTjg3S1REUVZidis0dkVMeW1GVmhuL2NwM3VqYjF3alhKN3M1NjRpRzNQR3IKL3VMaWg3NWxIVkhya1BKTy9hYkk1czJRMTgwcXZlamdtS0VCVXpVT3pXdHhaVEVXdHZHUjQ1Ui82dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c3de1d0d-e7f7-4019-ac4b-13a48db02e9e.k8s.ondigitalocean.com
  name: do-nyc1-k8s-inciativa
contexts:
- context:
    cluster: do-nyc1-k8s-inciativa
    user: do-nyc1-k8s-inciativa-admin
  name: do-nyc1-k8s-inciativa
current-context: do-nyc1-k8s-inciativa
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-inciativa-admin
  user:
    token: dop_v1_d6276385f9e9a84d653604a65dba59e5b860e7196c3b46299264c5f0a4b3c957
